blank_issues_enabled: false
contact_links:
  - name: Talk with Us on Slack
    url: https://slack.solo.io
    about: For a fast response, consider asking your question on the Solo slack.
  - name: Solo.io Documentation
    url: https://docs.solo.io/gloo-mesh-enterprise/latest/operations/troubleshooting
    about: Check out the Troubleshooting section of the Gloo Mesh docs.
